/*

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

My approach:
- use a nested for loop for a, and then b
- do an insert into a set (which will handle duplicates)
- return length of set

*/


let solutionRunner = (aMin, aMax, bMin, bMax) => {

  let terms = new Set();

  for (let a = aMin; a <= aMax; ++a) {

    for (let b = bMin; b <= bMax; ++b) {
      terms.add(Math.pow(a,b));
    }
  }

  return terms.size;
}

// solutionRunner(2, 5, 2, 5); // 15
solutionRunner(2, 100, 2, 100); // 15